project:
  type: website

execute:
    freeze: auto

website:
  title: "Lea K. Hildebrandt"
  navbar:
    background: secondary
    search: true
    right:
      - href: index.qmd
        text: Home
      - slides.qmd  
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



