---
title: "About"
---

I am a Postdoc working in the [Experimental Clinical Psychology Group](http://www.i1.psychologie.uni-wuerzburg.de/ekp/home/) at the University of Wuerzburg, Germany. Here I work on the mechanisms of social attention, specifically the effect of social presence, using virtual reality, eye tracking, and autonomic measures. I also work on a VR project investigating defensive responses (i.e. freezing, fight-or-flight) to threats. I currently supervise bachelor theses on a range of topics (see projects). I'm a strong proponent of open science practices, and love R and statistics.

I am also the coordinator of the [Research Training Group 2660](https://www.uni-wuerzburg.de/grk2660/). In this function, I am organizing events, workshops and a yearly summer school, have an open ear for the doctoral researchers, and am responsible for everything "behind the scenes" (Executive Board meetings, finances) to make the RTG run smoothly. I love this job.

In addition, I am currently training to become a systemic psychotherapist.
  
Previously, I did my PhD at the [Department for Social Neuroscience](http://www.cbs.mpg.de/abteilungen/soziale-neurowissenschaft/) at the MPI for Human Cognitive and Brain Sciences in Leipzig, where I worked (also using virtual reality and peripheral physiological measures) on a longitudinal study on the effects of mental training on emotion regulation. I have master's degrees both in Psychology and Neuroscience.
